### ISSUE TITLE
save button should open up file explorer to browse where to save

### ISSUE THREAD

**Issue by andezgrip** [eveninglily/drawingapp#17]
example http://i.imgur.com/sxT7QJR.png

**Comment by eveninglily** [comment]
Partially done by
https://github.com/McIntireEvan/drawingapp/commit/9504bfd723e009fce7a5665f42de5f759fc1d892
https://github.com/McIntireEvan/drawingapp/commit/9380152713fa080ce05cd5794446145e51b40699

It might be possible to get the file explorer, Ill have to see

**Comment by eveninglily** [comment]
This is a browser thing I can't fix - Under 'Advanced Options' in chrome, you can have it prompt you where to save things. Other browsers behave the same way. I can't do anything to change that, so I'm closing this
