### ISSUE TITLE
Settings Window

### ISSUE THREAD

**Issue by andezgrip** [eveninglily/drawingapp#21]

**Comment by eveninglily** [comment]
-Change hotkeys
-Change icon sizes, either 64x64 or 32x32
-Disable undo/redo

**Comment by eveninglily** [comment]
Will initially contain hotkey settings and icon size settings

**Comment by eveninglily** [comment]
https://github.com/McIntireEvan/drawingapp/commit/e4ff03b2fa791780d3aab187578822b174c2d30a adds keybindings, it still has to be improved some, but Im going to close this issue
