### ISSUE TITLE
put keyboard icons instead of the regular text in help menu

### ISSUE THREAD

**Issue by andezgrip** [eveninglily/drawingapp#35]
instead of something like ctrl+s put in the icons for ctrl and s

**Comment by eveninglily** [comment]
It might be better to do this with CSS to reduce page load time, I'll see

**Comment by notkaip** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd
You could style this element, designed for that purpose.

Also, this: http://meta.superuser.com/questions/4788/css-for-the-new-kbd-style
