### ISSUE TITLE
cursor should CONTINUE when entering/exiting canvas

### ISSUE THREAD

**Issue by andezgrip** [eveninglily/drawingapp#7]
for example
http://i.imgur.com/TRuMD4q.gif
to
http://i.imgur.com/YWspe8o.gif

the cursor should continue, because it gives a much more smooth drawing experience because it doesn't feel like the app freezes every time you draw on the edge

**Comment by eveninglily** [comment]
I changed some code to make the cursor disappear when you leave the mouse window while drawing, but making it completely like  Awwapp's is impossible unless you no longer want the cursor that shows the radius/the current color

**Comment by andezgrip** [comment]
have the cursor disappear once you leave canvas then
